# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'slide1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo1 = QtWidgets.QLabel(self.centralwidget)
        self.photo1.setGeometry(QtCore.QRect(0, 0, 801, 551))
        self.photo1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.photo1.setText("")
        self.photo1.setPixmap(QtGui.QPixmap("1.png"))
        self.photo1.setScaledContents(True)
        self.photo1.setObjectName("photo1")
        self.button1 = QtWidgets.QPushButton(self.centralwidget)
        self.button1.setGeometry(QtCore.QRect(180, 360, 141, 31))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(11)
        self.button1.setFont(font)
        self.button1.setObjectName("button1")
        self.button2 = QtWidgets.QPushButton(self.centralwidget)
        self.button2.setGeometry(QtCore.QRect(500, 360, 141, 31))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(11)
        self.button2.setFont(font)
        self.button2.setObjectName("button2")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(10, 0, 781, 181))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(12)
        self.label1.setFont(font)
        self.label1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label1.setObjectName("label1")
        self.label1.setStyleSheet("QLabel::hover"
                                  "{"
                                  "background-color : grey;"
                                  "}")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.button2.clicked.connect(lambda :self.checkout1('I began to stroll towards the strange thing in hesitation..\n'
                                                            'But what was it??? Definitely not an animal.\n'
                                                            'Scary situations pump in so much optimism into a person that I thought he was a hiker\n'
                                                            'who was either lost or separated from the rest of his group.\n'
                                                            'He began to crawl on his limbs like an animal\n'
                                                            'How could I believe my eyes? I ran towards the tent to call my friends.\n'
                                                            'And what did I see there?? NO ONE. I ran to see an empty tent. Where were they all?? WHAT WAS HAPPENING??!!\n'
                                                            'should I go in search of them?'))
        self.button1.clicked.connect(lambda :self.nah('oof Thank you'))#creat new method
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button1.setText(_translate("MainWindow", "nah back to tent "))
        self.button2.setText(_translate("MainWindow", "check it out"))
        self.label1.setText(_translate("MainWindow", "It had been a while since me and my friends went to hangout.\n"
" We were a group of five in the wilderness, exploring the beauty of nature in the dark. \n"
"We had a new person in the group who had brought us all here..\n"
"Something told me that this was a bad idea from the start\n"
"With the sun hiding behind the horizon, the wolves had begun to howl.\n"
" We decided to set up our camp and have a campfire in the front.Finally! \n"
"There was a place for us to rest. While we were all wrapping up for the night, I could not help but notice something strange. "))
    def checkout1(self,text):
        self.label1.setText(text)
        self.label1.setStyleSheet("QLabel::hover"
                            "{"
                            "background-color : grey;"
                            "}")
        self.label1.adjustSize()
        self.button2.setText('look out')
        self.button1.setText('run')
        self.photo1.setPixmap(QtGui.QPixmap("2.jpg"))
        self.button2.clicked.connect(lambda :self.checkout2('I began the search from close vicinity of the tent.\n'
                                                            ' I did not have the courage to go farther away.\n'
                                                            'As I went ahead, I noticed bloodstains all over the grass. Was it what I thought it was??\n'
                                                            'I lifted my head to see 4 corpses corpeses hanging down from a tree\n'
                                                            'I FREAKED OUT!!\n'
                                                            'should I run away?'))

    def nah(self,text):
        self.label1.setText(text)
        self.label1.adjustSize()
    def checkout2(self,text):
        self.label1.setText(text)
        self.label1.setStyleSheet("QLabel::hover"
                                  "{"
                                  "background-color : grey;"
                                  "}")
        self.label1.adjustSize()
        self.button2.setText('the truth')
        self.button1.setText('this needs to stop')
        self.button1.adjustSize()
        self.photo1.setPixmap(QtGui.QPixmap("4.jpg"))
        self.button2.clicked.connect(lambda: self.checkout3('Great! You want me to explore at the cost of my life. You are a kind person\n'
                                                            'Moving forward, I went close to the tree\n'
                                                            'I saw bear claw marks on the trunk\n'
                                                            'I heard a scream in the far distance\n'
                                                            'I began to follow the direction of the sound. To my surprise, \n'
                                                            'I ended up in exactly the same place where I had met the starnge man earlier.\n'
                                                            'Should I still keep looking?'))
        #add method to the nno option button

    def checkout3(self,text):
        self.label1.setText(text)
        self.label1.setStyleSheet("QLabel::hover"
                                  "{"
                                  "background-color : grey;"
                                  "}")
        self.label1.adjustSize()
        self.button2.setText('i have to save them')
        self.button2.adjustSize()
        self.button1.setText('they werent close either way')
        self.button1.adjustSize()
        self.photo1.setPixmap(QtGui.QPixmap("5.jpg"))
        self.button2.clicked.connect(lambda: self.checkout4('Very well. I was a victim of cannibalism you jerk. The man ripped me off dead!\n'
                                                            'may my soul rest in peace'))

    def checkout4(self,text):
        self.label1.setText(text)
        self.label1.setStyleSheet("QLabel::hover"
                                  "{"
                                  "background-color : grey;"
                                  "}")
        self.label1.adjustSize()
        self.button2.setText('exit')
        self.button1.setText('thank you')
        self.photo1.setPixmap(QtGui.QPixmap("6.jpg"))
        self.button2.clicked.connect(lambda: self.checkout5('yeah'))

    def checkout5(self,text):
        self.label1.setText(text)
        sys.exit()
        #creat somthing for end sys.exec_ somthing like that





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
